### PR TITLE
Change backend from `pysam` to `cyvcf2`

### PR DESCRIPTION
**Pull request by tedil**

### CODE REVIEW

**Comment by EQt** [comment]
Looks like cyvcf2 needs special compile flags [on MacOS](https://github.com/brentp/cyvcf2#github-building-htslib-and-cyvcf2-from-source). [Apparently](https://stackoverflow.com/a/72217172), it should suffice to set the environment variables accordingly

**Comment by EQt** [comment]
`cyvcf2` fixed the issue in the new version 0.30.16 (see https://github.com/brentp/cyvcf2/pull/246 )

**Comment by EQt** [comment]
After some manual tests I found that 
```sh
vembrane filter 'FORMAT["GT"]["S6"] == (None, 0)' tests/testcases/test_infotuple_comparison/test.vcf
```
is failing and smaller than the test_infotuple_comparison expression

**Comment by tedil** [comment]
> After some manual tests I found that
> 
> ```shell
> vembrane filter 'FORMAT["GT"]["S6"] == (None, 0)' tests/testcases/test_infotuple_comparison/test.vcf
> ```
> 
> is failing and smaller than the test_infotuple_comparison expression

Ah, sorry, forgot to mention: yes, both pysam and cyvcf special case `FORMAT["GT"]`, and they both do it differently. I have another branch (switchable-backends, local only atm) which special cases those special cases.

**Comment by EQt** [comment]
Elaborating on this it turns out that
```sh
vembrane filter 'print(repr(FORMAT["GT"]["S6"]))' tests/testcases/test_infotuple_comparison/test.vcf
```
on this  branch prints
```
InfoTuple(values=(NoValue(), 0))
```
whereas on main branch it prints
```
InfoTuple(values=(None, 0)
```

**Comment by EQt** [comment]
> Ah, sorry, forgot to mention: yes, both pysam and cyvcf special case `FORMAT["GT"]`, and they both do it differently. I have another branch (switchable-backends, local only atm) which special cases those special cases.

Is this pull request still relevant, then?

**Comment by tedil** [comment]
> > Ah, sorry, forgot to mention: yes, both pysam and cyvcf special case `FORMAT["GT"]`, and they both do it differently. I have another branch (switchable-backends, local only atm) which special cases those special cases.
> 
> Is this pull request still relevant, then?

Yes and no, a lot of the changes made here will also re-appear in the new branch. I'll see that I get it in a state where I can open a PR here.

**Comment by christopher-schroeder** [comment]
obsolete with v2.0

**Pull request closed without merging**
